"""Alterar de 'fone' para 'telefone' e de 'biografia' para 'bio' no model 'Autor'.

Revision ID: 452447d58ee5
Revises: 1ba5540b6ee3
Create Date: 2025-07-24 19:30:30.281296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452447d58ee5'
down_revision: Union[str, Sequence[str], None] = '1ba5540b6ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('autor', 'biografia', new_column_name='bio')
    op.alter_column('autor', 'fone', new_column_name='telefone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('autor', 'bio', new_column_name='biografia')
    op.alter_column('autor', 'telefone', new_column_name='fone')
    # ### end Alembic commands ###
