"""Alterar de 'fone' para 'telefone' no model 'Editora'.

Revision ID: 6e7ff45c75ce
Revises: 452447d58ee5
Create Date: 2025-07-24 19:57:26.207857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7ff45c75ce'
down_revision: Union[str, Sequence[str], None] = '452447d58ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('editora', 'fone', new_column_name='telefone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('editora', 'telefone', new_column_name='fone')
    # ### end Alembic commands ###
